"""Raw survey responses copied from the Google Form export."""

RAW_ROWS = [
    {
        "student": 1,
        "timestamp": "26.09.2026 22:05:34",
        "year": 2,
        "travel_raw": "120",
        "transport_raw": "Қоғамдық көлік(автобус) / Public transport (bus) / Общественный транспорт (автобус)",
        "attendance_raw": "95",
    },
    {
        "student": 2,
        "timestamp": "26.09.2026 22:09:41",
        "year": 2,
        "travel_raw": "2",
        "transport_raw": "Жеке көлік / такси, Personal car / taxi, Личное авто / такси",
        "attendance_raw": "99,90%",
    },
    {
        "student": 3,
        "timestamp": "26.09.2026 22:13:31",
        "year": 2,
        "travel_raw": "1 сағат",
        "transport_raw": "Қоғамдық көлік(автобус) / Public transport (bus) / Общественный транспорт (автобус)",
        "attendance_raw": "90",
    },
    {
        "student": 4,
        "timestamp": "26.09.2026 22:16:51",
        "year": 2,
        "travel_raw": "1.5 сағат",
        "transport_raw": "Қоғамдық көлік(автобус) / Public transport (bus) / Общественный транспорт (автобус)",
        "attendance_raw": "90%",
    },
    {
        "student": 5,
        "timestamp": "26.09.2026 22:19:03",
        "year": 2,
        "travel_raw": "20",
        "transport_raw": "Жаяу / On foot / Пешком",
        "attendance_raw": "100",
    },
    {
        "student": 6,
        "timestamp": "26.09.2026 22:39:29",
        "year": 1,
        "travel_raw": "5",
        "transport_raw": "Жаяу / On foot / Пешком",
        "attendance_raw": "100%",
    },
    {
        "student": 7,
        "timestamp": "26.09.2026 22:41:16",
        "year": 1,
        "travel_raw": "10-15 минут",
        "transport_raw": "Жаяу / On foot / Пешком",
        "attendance_raw": "90-100%",
    },
    {
        "student": 8,
        "timestamp": "26.09.2026 22:45:39",
        "year": 2,
        "travel_raw": "50",
        "transport_raw": "Қоғамдық көлік(автобус) / Public transport (bus) / Общественный транспорт (автобус)",
        "attendance_raw": "95",
    },
    {
        "student": 9,
        "timestamp": "26.09.2026 22:53:51",
        "year": 2,
        "travel_raw": "1 сағат",
        "transport_raw": "Қоғамдық көлік(автобус) / Public transport (bus) / Общественный транспорт (автобус)",
        "attendance_raw": "100%",
    },
    {
        "student": 10,
        "timestamp": "26.09.2026 22:53:51",
        "year": 2,
        "travel_raw": "20-30 минут",
        "transport_raw": "Жаяу / On foot / Пешком",
        "attendance_raw": "100%",
    },
    {
        "student": 11,
        "timestamp": "26.09.2026 22:56:46",
        "year": 4,
        "travel_raw": "20 мин",
        "transport_raw": "Жаяу / On foot / Пешком",
        "attendance_raw": "0%",
    },
    {
        "student": 12,
        "timestamp": "26.09.2026 22:57:58",
        "year": 2,
        "travel_raw": "30мин",
        "transport_raw": "Қоғамдық көлік(автобус) / Public transport (bus) / Общественный транспорт (автобус)",
        "attendance_raw": "67%",
    },
    {
        "student": 13,
        "timestamp": "26.09.2026 22:59:22",
        "year": 2,
        "travel_raw": "60 минут",
        "transport_raw": "Қоғамдық көлік(автобус) / Public transport (bus) / Общественный транспорт (автобус)",
        "attendance_raw": "100%",
    },
    {
        "student": 14,
        "timestamp": "26.09.2026 22:59:23",
        "year": 2,
        "travel_raw": "7 мин",
        "transport_raw": "Қоғамдық көлік(автобус) / Public transport (bus) / Общественный транспорт (автобус)",
        "attendance_raw": "100",
    },
    {
        "student": 15,
        "timestamp": "26.09.2026 23:00:03",
        "year": 1,
        "travel_raw": "50 минут",
        "transport_raw": "Қоғамдық көлік(автобус) / Public transport (bus) / Общественный транспорт (автобус)",
        "attendance_raw": "90",
    },
    {
        "student": 16,
        "timestamp": "26.09.2026 23:05:18",
        "year": 4,
        "travel_raw": "1 мин",
        "transport_raw": "Самолет",
        "attendance_raw": "80%",
    },
    {
        "student": 17,
        "timestamp": "26.09.2026 23:24:40",
        "year": 2,
        "travel_raw": "1 час",
        "transport_raw": "Қоғамдық көлік(автобус) / Public transport (bus) / Общественный транспорт (автобус)",
        "attendance_raw": "60%",
    },
    {
        "student": 18,
        "timestamp": "26.09.2026 23:40:48",
        "year": 4,
        "travel_raw": "Час",
        "transport_raw": "Қоғамдық көлік(автобус) / Public transport (bus) / Общественный транспорт (автобус)",
        "attendance_raw": "70%",
    },
    {
        "student": 19,
        "timestamp": "26.09.2026 23:43:35",
        "year": 3,
        "travel_raw": "15минут",
        "transport_raw": "Жаяу / On foot / Пешком",
        "attendance_raw": "97%",
    },
    {
        "student": 20,
        "timestamp": "26.09.2026 23:49:51",
        "year": 2,
        "travel_raw": "30-50",
        "transport_raw": "Қоғамдық көлік(автобус) / Public transport (bus) / Общественный транспорт (автобус)",
        "attendance_raw": "90-100",
    },
    {
        "student": 21,
        "timestamp": "26.09.2026 23:59:32",
        "year": 3,
        "travel_raw": "25-30 мин",
        "transport_raw": "Қоғамдық көлік(автобус) / Public transport (bus) / Общественный транспорт (автобус)",
        "attendance_raw": "100%",
    },
    {
        "student": 22,
        "timestamp": "27.09.2026 9:32:22",
        "year": 1,
        "travel_raw": "25 минут",
        "transport_raw": "Қоғамдық көлік(автобус) / Public transport (bus) / Общественный транспорт (автобус)",
        "attendance_raw": "70%",
    },
    {
        "student": 23,
        "timestamp": "27.09.2026 17:57:09",
        "year": 4,
        "travel_raw": "2сағат",
        "transport_raw": "Қоғамдық көлік(автобус) / Public transport (bus) / Общественный транспорт (автобус)",
        "attendance_raw": "90-100%",
    },
    {
        "student": 24,
        "timestamp": "27.09.2026 18:58:25",
        "year": 2,
        "travel_raw": "30",
        "transport_raw": "Қоғамдық көлік(автобус) / Public transport (bus) / Общественный транспорт (автобус)",
        "attendance_raw": "100",
    },
    {
        "student": 25,
        "timestamp": "27.09.2026 22:06:37",
        "year": 1,
        "travel_raw": "30 минут",
        "transport_raw": "20 минут пешком, 10 минут на автобусе",
        "attendance_raw": "100%",
    },
    {
        "student": 26,
        "timestamp": "01.10.2026 9:19:07",
        "year": 2,
        "travel_raw": "120 мин",
        "transport_raw": "Қоғамдық көлік(автобус) / Public transport (bus) / Общественный транспорт (автобус)",
        "attendance_raw": "90%",
    },
    {
        "student": 27,
        "timestamp": "01.10.2026 9:19:26",
        "year": 2,
        "travel_raw": "100",
        "transport_raw": "Қоғамдық көлік(автобус) / Public transport (bus) / Общественный транспорт (автобус)",
        "attendance_raw": "70",
    },
    {
        "student": 28,
        "timestamp": "01.10.2026 9:19:36",
        "year": 2,
        "travel_raw": "40",
        "transport_raw": "Қоғамдық көлік(автобус) / Public transport (bus) / Общественный транспорт (автобус)",
        "attendance_raw": "100%",
    },
    {
        "student": 29,
        "timestamp": "01.10.2026 9:20:29",
        "year": 3,
        "travel_raw": "60",
        "transport_raw": "Жеке көлік / такси, Personal car / taxi, Личное авто / такси",
        "attendance_raw": "80",
    },
    {
        "student": 30,
        "timestamp": "02.10.2026 9:29:51",
        "year": 1,
        "travel_raw": "75",
        "transport_raw": "Қоғамдық көлік(автобус) / Public transport (bus) / Общественный транспорт (автобус)",
        "attendance_raw": "80",
    },
    {
        "student": 31,
        "timestamp": "02.10.2026 9:30:09",
        "year": 4,
        "travel_raw": "20 мин",
        "transport_raw": "Жаяу / On foot / Пешком",
        "attendance_raw": "90",
    },
    {
        "student": 32,
        "timestamp": "02.10.2026 9:30:29",
        "year": 2,
        "travel_raw": "50",
        "transport_raw": "Жеке көлік / такси, Personal car / taxi, Личное авто / такси",
        "attendance_raw": "75",
    },
    {
        "student": 33,
        "timestamp": "02.10.2026 9:30:51",
        "year": 3,
        "travel_raw": "45",
        "transport_raw": "Жеке көлік / такси, Personal car / taxi, Личное авто / такси",
        "attendance_raw": "75",
    },
    {
        "student": 34,
        "timestamp": "02.10.2026 9:31:05",
        "year": 1,
        "travel_raw": "20",
        "transport_raw": "Жаяу / On foot / Пешком",
        "attendance_raw": "100",
    },
]
